### ISSUE TITLE
카카오맵 검색 시 rxjs debounce 

### ISSUE THREAD

**Issue by gene-ss** [BatShu/BatShu-front#10]
## 설명
매 글자 입력시마다 검색이 일어나는 비효율적인 api를 막기 위해 필요합니다.

**Comment by HYEOK9** [comment]
https://dev.to/mfp22/dont-use-rxjs-in-react-5f78
이거 작동방식이 immutable 아닌거 같은데 lodash에 비해 장점이있나?
api말고 input만 debounce해도 해결되긴 해서 일단 lodash로 대충 갈겨놨음ㅋhttps://github.com/BatShu/BatShu-front/commit/8259c37443139a36d1c8172f3d31c9935c358d01
아니면 [이거](https://react-rxjs.org) 쓰자는건가??

**Comment by gene-ss** [comment]
@HYEOK9 중요한 부분이 아니니까 간단하게만 해결해도 될듯~
