### ISSUE TITLE
Search 페이지에서 Map 모달 공통 활용

### ISSUE THREAD

**Issue by gene-ss** [BatShu/BatShu-front#11]
## 설명
모달을 이쁘게 만들어서 위치 검색시마다 돌려쓰자.

**Comment by HYEOK9** [comment]
absolute로 전체화면에 박고잇는데 포탈쓰는게 나아보임

**Comment by gene-ss** [comment]
@HYEOK9 지금 구현도 굳이 바꿀 정도는 아닌듯. 동의하면 close 해줘~
