### ISSUE TITLE
bug: grid2와 vite의 호환 문제

### ISSUE THREAD

**Issue by gene-ss** [BatShu/BatShu-front#7]
### 스크린샷
![image](https://github.com/BatShu/BatShu-front/assets/42014299/e31cdb60-32fb-4bbe-801d-87bb17734284)
![image](https://github.com/BatShu/BatShu-front/assets/42014299/6788af27-00b3-45ee-a0da-d2cc2bd6a1aa)
### 설명
grid2의 오류로 아무런 페이지가 나오지 않음.

## 재현 방법
- feature/api 브랜치 checkout 후 실행하면 나는 것 같은데. 재현이 가능한 이슈인지는 모르겠음.

## 관련 이슈
- https://github.com/vitejs/vite/issues/12423
- https://github.com/mui/material-ui/issues/32727

## 해결책
- 단기간에 해결될 문제가 아닐 것으로 보임. Grid2 사용을 멈추는 것은 어떤지

**Comment by HYEOK9** [comment]
Grid2 -> Grid로 변경
